trigger:
  - main  # Adjust according to your default branch

schedules:
  - cron: "0 0 * * *"  # Runs daily at midnight UTC
    displayName: Daily midnight build
    branches:
      include:
        - main
    always: true

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: GitHubCredentials

steps:
  - checkout: self
    persistCredentials: true

  - script: |
      git config --global user.name 'Nauman501'
      git config --global user.email 'kyaninauman229@gmail.com'
      git remote add github https://Nauman501:$(github_token)@github.com/Nauman501/AzureDevOpsGithub.git
      git fetch github main || true  # Fetch the remote state; ignore errors if branch doesn't exist
      git checkout -B main  # Create or switch to main branch
      git push github main --force-with-lease
    displayName: 'Push to GitHub'
    env:
      GITHUB_TOKEN: $(github_token)
