trigger:
  - master  # Adjust according to your default branch

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
    clean: true

  - script: |
      cd /home/vsts/work/1/s/
      git config --global user.name 'Nauman501'
      git config --global user.email 'kyaninauman229@gmail.com'
      git remote rm origin
      git remote add github https://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@github.com/Nauman501/AzureDevOpsGithub.git
      git push --force github master
    displayName: 'Push to GitHub'
