trigger:
  - main  # Adjust according to your default branch

pool:
  vmImage: 'windows-latest'

variables:
  GITHUB_TOKEN: $(GITHUB_TOKEN)  # Reference the GitHub PAT stored as a secret variable

steps:
  - checkout: self
    persistCredentials: true

  - script: |
      git config --global user.name 'Nauman501'
      git config --global user.email 'kyaninauman229@gmail.com'
      git remote add github https://$(GITHUB_TOKEN)@github.com/Nauman501/AzureDevOpsGithub.git
      git fetch github
      git checkout main || git checkout -b main
      git reset --hard github/main
      git push github main --force
    displayName: 'Push to GitHub'
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)
